server.port=8092

#БД
pkv.spring.datasource.jdbcUrl=jdbc:mysql://10.41.0.247:3306/pkv?useLegacyDatetimeCode=false&amp&serverTimezone=UTC
#?useSSL=false&useUnicode=true&us
pkv.spring.datasource.username=root
pkv.spring.datasource.password=654321
#автосоздание
pkv.spring.jpa.generate-ddl=true

#БД
asv.spring.datasource.driver-class-name=com.ibm.db2.jcc.DB2Driver
asv.spring.datasource.jdbcUrl=jdbc:db2://10.41.232.88:50000/ASV
asv.spring.datasource.username=db2inst
asv.spring.datasource.password=db2inst
asv.spring.jpa.hibernate.ddl-auto=none

spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=45MB

spring.thymeleaf.cache=false